
spring:
  datasource:
    url: jdbc:mysql://b256b206ac8263:7f7b13ed@us-cdbr-east-06.cleardb.net/heroku_48cf622b47df9e1?reconnect=true
    username: b256b206ac8263
    password: 7f7b13ed
    testOnBorrow: true
    validationQuery: SELECT 1

  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/emoney?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    driver: com.mysql.cj.jdbc.Driver
#    username: root
#    password: jljlkl890090

    hikari:
      maximum-pool-size: 10

jwt:
  secret: superverysecreykey