
spring:
  datasource:
#    url: jdbc:mysql://ec2-3-95-185-42.compute-1.amazonaws.com:3306/team6
#    username: root
#    password: G2labDana123*
    url: jdbc:mysql://b256b206ac8263:7f7b13ed@us-cdbr-east-06.cleardb.net/heroku_48cf622b47df9e1?reconnect=true
    username: b256b206ac8263
    password: 7f7b13ed
#    url: jdbc:mysql://localhost:3306/team6?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password: password
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10

  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

  main:
    banner-mode: off

  mail:
    host: smtp.gmail.com
    port: 587
    username: auto.emoney.app@gmail.com
    password: duatigaayamgoreng
    properties:
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.starttls.enable: true

server:
  port: 9706

phoneNumber: ${T6phoneNumber}
twilioAccountSid: ${T6twilioAccountSid}
twilioAuthToken: ${T6twilioAuthToken}