
spring:
  datasource:
    url: jdbc:mysql://b256b206ac8263:7f7b13ed@us-cdbr-east-06.cleardb.net/heroku_48cf622b47df9e1?reconnect=true
    username: b256b206ac8263
    password: 7f7b13ed

    hikari:
      maximum-pool-size: 10

jwt:
  secret: superverysecreykey