
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team6
    username: root
    password: G2labDana123*
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

    hikari:
      maximum-pool-size: 10
