
spring:
  datasource:
    url: jdbc:mysql://b256b206ac8263:7f7b13ed@us-cdbr-east-06.cleardb.net/heroku_48cf622b47df9e1?reconnect=true
    username: b256b206ac8263
    password: 7f7b13ed

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/emoney?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    driver: com.mysql.cj.jdbc.Driver
#    username: root
#    password: jljlkl890090

    hikari:
      maximum-pool-size: 10

jwt:
  secret: superverysecreykey

phoneNumber: +12058439958
twilioAccountSid: ACc9524830957a04cfdc9851c0392aacb9
twilioAuthToken: 80d5a54ff172be4509222ebbd9239b33
CLOUDAMQP_URL: amqp://wmaqowtk:SFX4rWejOk-3zCznHjw0PJZFFwHnqath@zebra.rmq.cloudamqp.com/wmaqowtk
userMQ: nabila