
spring:
  datasource:
    url: jdbc:mysql://b256b206ac8263:7f7b13ed@us-cdbr-east-06.cleardb.net/heroku_48cf622b47df9e1?reconnect=true
    username: b256b206ac8263
    password: 7f7b13ed
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

  main:
    hikari:
      maximum-pool-size: 10
    banner-mode: off

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${T6mail.username}
    password: ${T6mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.starttls.enable: true
